import type { Age, EnergySource, Purchase, Technology } from './types';

export const assetPath = (fileName: string) => `/assets/game/${fileName}`;

export const energySources: EnergySource[] = [
  {
    id: 'biomass',
    ageId: 'biomass',
    label: 'Biomasse',
    shortLabel: 'Bio',
    color: '#2f8d64',
    clickContribution: 2,
    passiveContribution: 0,
  },
  {
    id: 'animal-power',
    ageId: 'animal-power',
    label: 'Élevage / force animale',
    shortLabel: 'Animal',
    color: '#8f6f3d',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'water-wind',
    ageId: 'water-wind',
    label: 'Eau et vent',
    shortLabel: 'Moulins',
    color: '#3a83a5',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'fossil',
    ageId: 'fossil',
    label: 'Fossile / vapeur',
    shortLabel: 'Fossile',
    color: '#5e6872',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'atomic',
    ageId: 'atomic',
    label: 'Énergie de l’atome',
    shortLabel: 'Atome',
    color: '#7b62c9',
    clickContribution: 0,
    passiveContribution: 0,
  },
];

export const ages: Age[] = [
  {
    id: 'biomass',
    label: 'Préhistoire',
    sourceId: 'biomass',
    advanceCostJoules: 120,
    description: 'Source nouvelle : biomasse.',
  },
  {
    id: 'animal-power',
    label: 'Néolithique',
    sourceId: 'animal-power',
    advanceCostJoules: 780,
    description: 'Source nouvelle : élevage et force animale.',
  },
  {
    id: 'water-wind',
    label: 'Moyen Âge',
    sourceId: 'water-wind',
    advanceCostJoules: 4200,
    description: 'Source nouvelle : moulins à eau et à vent.',
  },
  {
    id: 'fossil',
    label: 'Âge industriel',
    sourceId: 'fossil',
    advanceCostJoules: 22000,
    description: 'Source nouvelle : énergie fossile.',
  },
  {
    id: 'atomic',
    label: 'Âge atomique',
    sourceId: 'atomic',
    description: 'Source nouvelle : atome, synthèse dense du système.',
  },
];

export const purchases: Purchase[] = [
  {
    id: 'campfire',
    ageId: 'biomass',
    label: 'Feu de camp',
    sourceId: 'biomass',
    description: 'Le premier objet énergétique : bois, chaleur, nourriture.',
    costJoules: 18,
    clickGain: 2,
    passiveGain: 0.2,
    assetFile: 'campfire.png',
    impactLabel: '+2 J/clic · +0.2 J/s',
  },
  {
    id: 'stone-hearth',
    ageId: 'animal-power',
    label: 'Foyer en pierre',
    sourceId: 'biomass',
    description: 'La biomasse reste centrale, mais devient plus stable.',
    costJoules: 95,
    clickGain: 2,
    passiveGain: 0.8,
    assetFile: 'stone-hearth.png',
    impactLabel: '+2 J/clic · +0.8 J/s',
  },
  {
    id: 'oxen',
    ageId: 'animal-power',
    label: 'Bœufs de traction',
    sourceId: 'animal-power',
    description: 'L’élevage ajoute une nouvelle force utile au village.',
    costJoules: 180,
    clickGain: 3,
    passiveGain: 1.4,
    assetFile: 'ox.png',
    impactLabel: '+3 J/clic · +1.4 J/s',
  },
  {
    id: 'charcoal-kiln',
    ageId: 'water-wind',
    label: 'Four à charbon de bois',
    sourceId: 'biomass',
    description: 'Le bois devient un combustible plus concentré.',
    costJoules: 520,
    clickGain: 3,
    passiveGain: 2.4,
    assetFile: 'logs.png',
    impactLabel: '+3 J/clic · +2.4 J/s',
  },
  {
    id: 'heavy-plough',
    ageId: 'water-wind',
    label: 'Charrue lourde',
    sourceId: 'animal-power',
    description: 'La traction animale travaille mieux les sols lourds.',
    costJoules: 760,
    clickGain: 2,
    passiveGain: 4.2,
    assetFile: 'plough.png',
    impactLabel: '+2 J/clic · +4.2 J/s',
  },
  {
    id: 'watermill',
    ageId: 'water-wind',
    label: 'Moulin à eau',
    sourceId: 'water-wind',
    description: 'La rivière apporte une puissance mécanique continue.',
    costJoules: 1050,
    clickGain: 0,
    passiveGain: 8,
    assetFile: 'water-wheel.png',
    impactLabel: '+8 J/s',
  },
  {
    id: 'wood-gasifier',
    ageId: 'fossil',
    label: 'Gazogène à bois',
    sourceId: 'biomass',
    description: 'La biomasse reste utile comme gaz combustible industriel.',
    costJoules: 2600,
    clickGain: 5,
    passiveGain: 8,
    assetFile: 'boiler.png',
    impactLabel: '+5 J/clic · +8 J/s',
  },
  {
    id: 'relay-stables',
    ageId: 'fossil',
    label: 'Relais de chevaux',
    sourceId: 'animal-power',
    description: 'Les animaux restent utiles pour déplacer hommes et matières.',
    costJoules: 3400,
    clickGain: 4,
    passiveGain: 7,
    assetFile: 'horse.png',
    impactLabel: '+4 J/clic · +7 J/s',
  },
  {
    id: 'wind-pump',
    ageId: 'fossil',
    label: 'Pompe à vent',
    sourceId: 'water-wind',
    description: 'Le vent continue à rendre service au système productif.',
    costJoules: 4300,
    clickGain: 0,
    passiveGain: 16,
    assetFile: 'windmill.png',
    impactLabel: '+16 J/s',
  },
  {
    id: 'steam-engine',
    ageId: 'fossil',
    label: 'Machine à vapeur',
    sourceId: 'fossil',
    description: 'Le fossile débloque une densité énergétique massive.',
    costJoules: 6200,
    clickGain: 12,
    passiveGain: 34,
    assetFile: 'steam-engine.png',
    impactLabel: '+12 J/clic · +34 J/s',
  },
  {
    id: 'biogas-digester',
    ageId: 'atomic',
    label: 'Digesteur biogaz',
    sourceId: 'biomass',
    description: 'La biomasse reste présente sous une forme plus contrôlée.',
    costJoules: 14000,
    clickGain: 0,
    passiveGain: 42,
    assetFile: 'food-cache.png',
    impactLabel: '+42 J/s',
  },
  {
    id: 'feed-logistics',
    ageId: 'atomic',
    label: 'Logistique alimentaire',
    sourceId: 'animal-power',
    description: 'L’élevage devient une organisation de flux et de nourriture.',
    costJoules: 17000,
    clickGain: 0,
    passiveGain: 36,
    assetFile: 'granary.png',
    impactLabel: '+36 J/s',
  },
  {
    id: 'hydro-wind-grid',
    ageId: 'atomic',
    label: 'Réseau hydro-éolien',
    sourceId: 'water-wind',
    description: 'Eau et vent restent dans le mix, mieux raccordés.',
    costJoules: 21000,
    clickGain: 0,
    passiveGain: 70,
    assetFile: 'windmill.png',
    impactLabel: '+70 J/s',
  },
  {
    id: 'thermal-turbine',
    ageId: 'atomic',
    label: 'Turbine thermique',
    sourceId: 'fossil',
    description: 'Le fossile devient un appoint puissant, mais plus encadré.',
    costJoules: 26000,
    clickGain: 14,
    passiveGain: 82,
    assetFile: 'small-factory.png',
    impactLabel: '+14 J/clic · +82 J/s',
  },
  {
    id: 'reactor-core',
    ageId: 'atomic',
    label: 'Cœur de réacteur',
    sourceId: 'atomic',
    description: 'L’atome rassemble le système autour d’une source très dense.',
    costJoules: 36000,
    clickGain: 0,
    passiveGain: 260,
    impactLabel: '+260 J/s',
  },
];

export const technologies: Technology[] = [
  {
    id: 'ember-keeping',
    ageId: 'biomass',
    label: 'Conservation de la braise',
    sourceId: 'biomass',
    targetPurchaseId: 'campfire',
    costJoules: 42,
    clickGain: 1,
    passiveGain: 0.4,
    assetFile: 'fire-glow.png',
    impactLabel: '+1 J/clic · +0.4 J/s',
  },
  {
    id: 'masonry-hearth',
    ageId: 'animal-power',
    label: 'Foyer maçonné',
    sourceId: 'biomass',
    targetPurchaseId: 'stone-hearth',
    costJoules: 140,
    clickGain: 1,
    passiveGain: 0.9,
    assetFile: 'stone-hearth.png',
    impactLabel: '+1 J/clic · +0.9 J/s',
  },
  {
    id: 'animal-domestication',
    ageId: 'animal-power',
    label: 'Domestication de traction',
    sourceId: 'animal-power',
    targetPurchaseId: 'oxen',
    costJoules: 260,
    clickGain: 2,
    passiveGain: 1.8,
    assetFile: 'ox.png',
    impactLabel: '+2 J/clic · +1.8 J/s',
  },
  {
    id: 'charcoal-craft',
    ageId: 'water-wind',
    label: 'Charbonnage',
    sourceId: 'biomass',
    targetPurchaseId: 'charcoal-kiln',
    costJoules: 820,
    clickGain: 2,
    passiveGain: 2.8,
    assetFile: 'logs.png',
    impactLabel: '+2 J/clic · +2.8 J/s',
  },
  {
    id: 'shoulder-collar',
    ageId: 'water-wind',
    label: 'Collier d’épaule',
    sourceId: 'animal-power',
    targetPurchaseId: 'heavy-plough',
    costJoules: 980,
    clickGain: 1,
    passiveGain: 4.4,
    assetFile: 'horse.png',
    impactLabel: '+1 J/clic · +4.4 J/s',
  },
  {
    id: 'wind-gears',
    ageId: 'water-wind',
    label: 'Moulin à vent',
    sourceId: 'water-wind',
    targetPurchaseId: 'watermill',
    costJoules: 1300,
    clickGain: 0,
    passiveGain: 10,
    assetFile: 'windmill.png',
    impactLabel: '+10 J/s',
  },
  {
    id: 'wood-gas-process',
    ageId: 'fossil',
    label: 'Gaz de bois',
    sourceId: 'biomass',
    targetPurchaseId: 'wood-gasifier',
    costJoules: 3600,
    clickGain: 3,
    passiveGain: 9,
    assetFile: 'boiler.png',
    impactLabel: '+3 J/clic · +9 J/s',
  },
  {
    id: 'horse-logistics',
    ageId: 'fossil',
    label: 'Haras logistiques',
    sourceId: 'animal-power',
    targetPurchaseId: 'relay-stables',
    costJoules: 4100,
    clickGain: 2,
    passiveGain: 8,
    assetFile: 'horse.png',
    impactLabel: '+2 J/clic · +8 J/s',
  },
  {
    id: 'mechanical-pumps',
    ageId: 'fossil',
    label: 'Pompes mécaniques',
    sourceId: 'water-wind',
    targetPurchaseId: 'wind-pump',
    costJoules: 5200,
    clickGain: 0,
    passiveGain: 20,
    assetFile: 'windmill.png',
    impactLabel: '+20 J/s',
  },
  {
    id: 'high-pressure-steam',
    ageId: 'fossil',
    label: 'Vapeur haute pression',
    sourceId: 'fossil',
    targetPurchaseId: 'steam-engine',
    costJoules: 7600,
    clickGain: 8,
    passiveGain: 46,
    assetFile: 'steam-engine.png',
    impactLabel: '+8 J/clic · +46 J/s',
  },
  {
    id: 'biogas-process',
    ageId: 'atomic',
    label: 'Méthanisation',
    sourceId: 'biomass',
    targetPurchaseId: 'biogas-digester',
    costJoules: 18000,
    clickGain: 0,
    passiveGain: 54,
    assetFile: 'food-cache.png',
    impactLabel: '+54 J/s',
  },
  {
    id: 'feed-chain',
    ageId: 'atomic',
    label: 'Chaîne alimentaire',
    sourceId: 'animal-power',
    targetPurchaseId: 'feed-logistics',
    costJoules: 21000,
    clickGain: 0,
    passiveGain: 48,
    assetFile: 'granary.png',
    impactLabel: '+48 J/s',
  },
  {
    id: 'modern-wind-turbines',
    ageId: 'atomic',
    label: 'Éoliennes modernes',
    sourceId: 'water-wind',
    targetPurchaseId: 'hydro-wind-grid',
    costJoules: 28000,
    clickGain: 0,
    passiveGain: 120,
    assetFile: 'windmill.png',
    impactLabel: '+120 J/s',
  },
  {
    id: 'thermal-cycle',
    ageId: 'atomic',
    label: 'Cycle thermique',
    sourceId: 'fossil',
    targetPurchaseId: 'thermal-turbine',
    costJoules: 34000,
    clickGain: 8,
    passiveGain: 100,
    assetFile: 'small-factory.png',
    impactLabel: '+8 J/clic · +100 J/s',
  },
  {
    id: 'controlled-fission',
    ageId: 'atomic',
    label: 'Fission contrôlée',
    sourceId: 'atomic',
    targetPurchaseId: 'reactor-core',
    costJoules: 48000,
    clickGain: 0,
    passiveGain: 360,
    impactLabel: '+360 J/s',
  },
];
