import type { Age, EnergySource, Purchase, Technology } from './types';

export const assetPath = (fileName: string) => `/assets/game/${fileName}`;

export const energySources: EnergySource[] = [
  {
    id: 'biomass',
    ageId: 'biomass',
    label: 'Biomasse',
    shortLabel: 'Bio',
    color: '#2f8d64',
    clickContribution: 2,
    passiveContribution: 0,
  },
  {
    id: 'animal-power',
    ageId: 'animal-power',
    label: 'Élevage / force animale',
    shortLabel: 'Animal',
    color: '#8f6f3d',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'water-wind',
    ageId: 'water-wind',
    label: 'Eau et vent',
    shortLabel: 'Moulins',
    color: '#3a83a5',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'fossil',
    ageId: 'fossil',
    label: 'Fossile / vapeur',
    shortLabel: 'Fossile',
    color: '#5e6872',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'atomic',
    ageId: 'atomic',
    label: 'Énergie de l’atome',
    shortLabel: 'Atome',
    color: '#7b62c9',
    clickContribution: 0,
    passiveContribution: 0,
  },
];

export const ages: Age[] = [
  {
    id: 'biomass',
    label: 'Préhistoire',
    sourceId: 'biomass',
    advanceCostJoules: 70,
    description: 'Feu et biomasse pour démarrer.',
  },
  {
    id: 'animal-power',
    label: 'Antiquité',
    sourceId: 'animal-power',
    advanceCostJoules: 320,
    description: 'Force animale pour produire et transporter.',
  },
  {
    id: 'water-wind',
    label: 'Moyen Âge',
    sourceId: 'water-wind',
    advanceCostJoules: 1800,
    description: 'Eau et vent font tourner les moulins.',
  },
  {
    id: 'fossil',
    label: 'Âge industriel',
    sourceId: 'fossil',
    advanceCostJoules: 7200,
    description: 'Vapeur et fossiles accélèrent la production.',
  },
  {
    id: 'atomic',
    label: 'Âge atomique',
    sourceId: 'atomic',
    description: 'L’atome apporte une énergie très dense.',
  },
];

export const purchases: Purchase[] = [
  {
    id: 'campfire',
    ageId: 'biomass',
    label: 'Feu de camp',
    sourceId: 'biomass',
    description: 'Le premier objet énergétique : bois, chaleur, nourriture.',
    costJoules: 12,
    clickGain: 3,
    passiveGain: 0.4,
    assetFile: 'campfire.png',
    impactLabel: '+3 J/clic · +0.4 J/s',
  },
  {
    id: 'stone-hearth',
    ageId: 'animal-power',
    label: 'Foyer en pierre',
    sourceId: 'biomass',
    description: 'La biomasse reste centrale, mais devient plus stable.',
    costJoules: 65,
    clickGain: 2,
    passiveGain: 1.2,
    assetFile: 'stone-hearth.png',
    impactLabel: '+2 J/clic · +1.2 J/s',
  },
  {
    id: 'oxen',
    ageId: 'animal-power',
    label: 'Bœufs de traction',
    sourceId: 'animal-power',
    description: 'L’élevage ajoute une nouvelle force utile au village.',
    costJoules: 95,
    clickGain: 4,
    passiveGain: 2.2,
    assetFile: 'ox.png',
    impactLabel: '+4 J/clic · +2.2 J/s',
  },
  {
    id: 'charcoal-kiln',
    ageId: 'water-wind',
    label: 'Four à charbon de bois',
    sourceId: 'biomass',
    description: 'Le bois devient un combustible plus concentré.',
    costJoules: 240,
    clickGain: 4,
    passiveGain: 6,
    assetFile: 'logs.png',
    impactLabel: '+4 J/clic · +6 J/s',
  },
  {
    id: 'heavy-plough',
    ageId: 'water-wind',
    label: 'Charrue lourde',
    sourceId: 'animal-power',
    description: 'La traction animale travaille mieux les sols lourds.',
    costJoules: 340,
    clickGain: 3,
    passiveGain: 8,
    assetFile: 'plough.png',
    impactLabel: '+3 J/clic · +8 J/s',
  },
  {
    id: 'watermill',
    ageId: 'water-wind',
    label: 'Moulin à eau',
    sourceId: 'water-wind',
    description: 'La rivière apporte une puissance mécanique continue.',
    costJoules: 480,
    clickGain: 0,
    passiveGain: 18,
    assetFile: 'water-wheel.png',
    impactLabel: '+18 J/s',
  },
  {
    id: 'wood-gasifier',
    ageId: 'fossil',
    label: 'Gazogène à bois',
    sourceId: 'biomass',
    description: 'La biomasse reste utile comme gaz combustible industriel.',
    costJoules: 1100,
    clickGain: 6,
    passiveGain: 18,
    assetFile: 'boiler.png',
    impactLabel: '+6 J/clic · +18 J/s',
  },
  {
    id: 'relay-stables',
    ageId: 'fossil',
    label: 'Relais de chevaux',
    sourceId: 'animal-power',
    description: 'Les animaux restent utiles pour déplacer hommes et matières.',
    costJoules: 1400,
    clickGain: 5,
    passiveGain: 16,
    assetFile: 'horse.png',
    impactLabel: '+5 J/clic · +16 J/s',
  },
  {
    id: 'wind-pump',
    ageId: 'fossil',
    label: 'Pompe à vent',
    sourceId: 'water-wind',
    description: 'Le vent continue à rendre service au système productif.',
    costJoules: 1650,
    clickGain: 0,
    passiveGain: 38,
    assetFile: 'windmill.png',
    impactLabel: '+38 J/s',
  },
  {
    id: 'steam-engine',
    ageId: 'fossil',
    label: 'Machine à vapeur',
    sourceId: 'fossil',
    description: 'Le fossile débloque une densité énergétique massive.',
    costJoules: 2200,
    clickGain: 14,
    passiveGain: 72,
    assetFile: 'steam-engine.png',
    impactLabel: '+14 J/clic · +72 J/s',
  },
  {
    id: 'biogas-digester',
    ageId: 'atomic',
    label: 'Digesteur biogaz',
    sourceId: 'biomass',
    description: 'La biomasse reste présente sous une forme plus contrôlée.',
    costJoules: 4200,
    clickGain: 0,
    passiveGain: 80,
    assetFile: 'food-cache.png',
    impactLabel: '+80 J/s',
  },
  {
    id: 'feed-logistics',
    ageId: 'atomic',
    label: 'Logistique alimentaire',
    sourceId: 'animal-power',
    description: 'L’élevage devient une organisation de flux et de nourriture.',
    costJoules: 5200,
    clickGain: 0,
    passiveGain: 70,
    assetFile: 'granary.png',
    impactLabel: '+70 J/s',
  },
  {
    id: 'hydro-wind-grid',
    ageId: 'atomic',
    label: 'Réseau hydro-éolien',
    sourceId: 'water-wind',
    description: 'Eau et vent restent dans le mix, mieux raccordés.',
    costJoules: 6400,
    clickGain: 0,
    passiveGain: 130,
    assetFile: 'windmill.png',
    impactLabel: '+130 J/s',
  },
  {
    id: 'thermal-turbine',
    ageId: 'atomic',
    label: 'Turbine thermique',
    sourceId: 'fossil',
    description: 'Le fossile devient un appoint puissant, mais plus encadré.',
    costJoules: 7600,
    clickGain: 16,
    passiveGain: 160,
    assetFile: 'small-factory.png',
    impactLabel: '+16 J/clic · +160 J/s',
  },
  {
    id: 'reactor-core',
    ageId: 'atomic',
    label: 'Cœur de réacteur',
    sourceId: 'atomic',
    description: 'L’atome rassemble le système autour d’une source très dense.',
    costJoules: 9800,
    clickGain: 0,
    passiveGain: 420,
    assetFile: 'images-finales-gpt-image/atomic/island-atomic-05-built-reactor-core.png',
    impactLabel: '+420 J/s',
  },
];

export const technologies: Technology[] = [
  {
    id: 'ember-keeping',
    ageId: 'biomass',
    label: 'Conservation de la braise',
    sourceId: 'biomass',
    targetPurchaseId: 'campfire',
    costJoules: 24,
    clickGain: 2,
    passiveGain: 0.8,
    assetFile: 'fire-glow.png',
    impactLabel: '+2 J/clic · +0.8 J/s',
  },
  {
    id: 'masonry-hearth',
    ageId: 'animal-power',
    label: 'Foyer maçonné',
    sourceId: 'biomass',
    targetPurchaseId: 'stone-hearth',
    costJoules: 95,
    clickGain: 2,
    passiveGain: 1.5,
    assetFile: 'stone-hearth.png',
    impactLabel: '+2 J/clic · +1.5 J/s',
  },
  {
    id: 'animal-domestication',
    ageId: 'animal-power',
    label: 'Domestication de traction',
    sourceId: 'animal-power',
    targetPurchaseId: 'oxen',
    costJoules: 130,
    clickGain: 2,
    passiveGain: 2.4,
    assetFile: 'ox.png',
    impactLabel: '+2 J/clic · +2.4 J/s',
  },
  {
    id: 'charcoal-craft',
    ageId: 'water-wind',
    label: 'Charbonnage',
    sourceId: 'biomass',
    targetPurchaseId: 'charcoal-kiln',
    costJoules: 340,
    clickGain: 3,
    passiveGain: 6,
    assetFile: 'logs.png',
    impactLabel: '+3 J/clic · +6 J/s',
  },
  {
    id: 'shoulder-collar',
    ageId: 'water-wind',
    label: 'Collier d’épaule',
    sourceId: 'animal-power',
    targetPurchaseId: 'heavy-plough',
    costJoules: 440,
    clickGain: 2,
    passiveGain: 8,
    assetFile: 'horse.png',
    impactLabel: '+2 J/clic · +8 J/s',
  },
  {
    id: 'wind-gears',
    ageId: 'water-wind',
    label: 'Moulin à vent',
    sourceId: 'water-wind',
    targetPurchaseId: 'watermill',
    costJoules: 560,
    clickGain: 0,
    passiveGain: 16,
    assetFile: 'windmill.png',
    impactLabel: '+16 J/s',
  },
  {
    id: 'wood-gas-process',
    ageId: 'fossil',
    label: 'Gaz de bois',
    sourceId: 'biomass',
    targetPurchaseId: 'wood-gasifier',
    costJoules: 1300,
    clickGain: 4,
    passiveGain: 18,
    assetFile: 'boiler.png',
    impactLabel: '+4 J/clic · +18 J/s',
  },
  {
    id: 'horse-logistics',
    ageId: 'fossil',
    label: 'Haras logistiques',
    sourceId: 'animal-power',
    targetPurchaseId: 'relay-stables',
    costJoules: 1500,
    clickGain: 3,
    passiveGain: 16,
    assetFile: 'horse.png',
    impactLabel: '+3 J/clic · +16 J/s',
  },
  {
    id: 'mechanical-pumps',
    ageId: 'fossil',
    label: 'Pompes mécaniques',
    sourceId: 'water-wind',
    targetPurchaseId: 'wind-pump',
    costJoules: 1800,
    clickGain: 0,
    passiveGain: 40,
    assetFile: 'windmill.png',
    impactLabel: '+40 J/s',
  },
  {
    id: 'high-pressure-steam',
    ageId: 'fossil',
    label: 'Vapeur haute pression',
    sourceId: 'fossil',
    targetPurchaseId: 'steam-engine',
    costJoules: 2400,
    clickGain: 10,
    passiveGain: 90,
    assetFile: 'steam-engine.png',
    impactLabel: '+10 J/clic · +90 J/s',
  },
  {
    id: 'biogas-process',
    ageId: 'atomic',
    label: 'Méthanisation',
    sourceId: 'biomass',
    targetPurchaseId: 'biogas-digester',
    costJoules: 5000,
    clickGain: 0,
    passiveGain: 95,
    assetFile: 'food-cache.png',
    impactLabel: '+95 J/s',
  },
  {
    id: 'feed-chain',
    ageId: 'atomic',
    label: 'Chaîne alimentaire',
    sourceId: 'animal-power',
    targetPurchaseId: 'feed-logistics',
    costJoules: 6000,
    clickGain: 0,
    passiveGain: 85,
    assetFile: 'granary.png',
    impactLabel: '+85 J/s',
  },
  {
    id: 'modern-wind-turbines',
    ageId: 'atomic',
    label: 'Éoliennes modernes',
    sourceId: 'water-wind',
    targetPurchaseId: 'hydro-wind-grid',
    costJoules: 7400,
    clickGain: 0,
    passiveGain: 180,
    assetFile: 'windmill.png',
    impactLabel: '+180 J/s',
  },
  {
    id: 'thermal-cycle',
    ageId: 'atomic',
    label: 'Cycle thermique',
    sourceId: 'fossil',
    targetPurchaseId: 'thermal-turbine',
    costJoules: 8600,
    clickGain: 10,
    passiveGain: 200,
    assetFile: 'small-factory.png',
    impactLabel: '+10 J/clic · +200 J/s',
  },
  {
    id: 'controlled-fission',
    ageId: 'atomic',
    label: 'Fission contrôlée',
    sourceId: 'atomic',
    targetPurchaseId: 'reactor-core',
    costJoules: 11500,
    clickGain: 0,
    passiveGain: 520,
    assetFile: 'images-finales-gpt-image/atomic/island-atomic-05-upgraded-controlled-fission.png',
    impactLabel: '+520 J/s',
  },
];
