import type { Age, BreakthroughMilestone, EnergySource, Purchase, Technology } from './types';

export const assetPath = (fileName: string) => `/assets/game/${fileName}`;

const FINAL_IMAGE_VERSION = '20260619-cosmic-v4';

export const finalImagePath = (fileName: string) =>
  `images-finales-gpt-image/${fileName}?v=${FINAL_IMAGE_VERSION}`;

const ORBITAL_SOLAR_ASSET = finalImagePath('orbital-solar/island-orbital-solar-07-built-collector.png');
const FUSION_ASSET = finalImagePath('atomic/island-atomic-07-built-fusion-plant.png');
const FUSION_UPGRADED_ASSET = finalImagePath('atomic/island-atomic-07-upgraded-controlled-fusion.png');
const ANTIMATTER_ASSET = finalImagePath('atomic/island-atomic-08-built-antimatter.png');
const ANTIMATTER_UPGRADED_ASSET = finalImagePath('atomic/island-atomic-08-upgraded-antimatter-containment.png');
const DYSON_ASSET = finalImagePath('dyson/island-dyson-11-built-stellar-swarm.png');

export const energySources: EnergySource[] = [
  {
    id: 'biomass',
    ageId: 'biomass',
    label: 'Biomasse',
    shortLabel: 'Bio',
    color: '#2f8d64',
    clickContribution: 2,
    passiveContribution: 0,
  },
  {
    id: 'animal-power',
    ageId: 'animal-power',
    label: 'Élevage / force animale',
    shortLabel: 'Animal',
    color: '#8f6f3d',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'water-wind',
    ageId: 'water-wind',
    label: 'Eau et vent',
    shortLabel: 'Moulins',
    color: '#3a83a5',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'fossil',
    ageId: 'fossil',
    label: 'Fossile / vapeur',
    shortLabel: 'Fossile',
    color: '#5e6872',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'atomic',
    ageId: 'atomic',
    label: 'Énergie de l’atome',
    shortLabel: 'Atome',
    color: '#7b62c9',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'fusion',
    ageId: 'fusion',
    label: 'Fusion contrôlée',
    shortLabel: 'Fusion',
    color: '#2d9fcf',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'orbital-solar',
    ageId: 'orbital-solar',
    label: 'Solaire orbital',
    shortLabel: 'Orbital',
    color: '#d7a72d',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'neutron-wells',
    ageId: 'neutron-wells',
    label: 'Puits de neutrons',
    shortLabel: 'Neutrons',
    color: '#4261b9',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'antimatter',
    ageId: 'antimatter',
    label: 'Antimatière',
    shortLabel: 'Antim.',
    color: '#a152d1',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'black-hole',
    ageId: 'black-hole',
    label: 'Siphon de trou noir',
    shortLabel: 'Trou noir',
    color: '#2c2a37',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'dyson',
    ageId: 'dyson',
    label: 'Sphère de Dyson',
    shortLabel: 'Dyson',
    color: '#e3b54f',
    clickContribution: 0,
    passiveContribution: 0,
  },
  {
    id: 'vacuum',
    ageId: 'vacuum',
    label: 'Énergie du vide',
    shortLabel: 'Vide',
    color: '#58c7b3',
    clickContribution: 0,
    passiveContribution: 0,
  },
];

export const ages: Age[] = [
  {
    id: 'biomass',
    label: 'Préhistoire',
    sourceId: 'biomass',
    advanceCostJoules: 90,
    description: 'Feu et biomasse pour démarrer.',
  },
  {
    id: 'animal-power',
    label: 'Antiquité',
    sourceId: 'animal-power',
    advanceCostJoules: 700,
    description: 'Force animale pour produire et transporter.',
  },
  {
    id: 'water-wind',
    label: 'Moyen Âge',
    sourceId: 'water-wind',
    advanceCostJoules: 2200,
    description: 'Eau et vent font tourner les moulins.',
  },
  {
    id: 'fossil',
    label: 'Âge industriel',
    sourceId: 'fossil',
    advanceCostJoules: 10000,
    description: 'Vapeur et fossiles accélèrent la production.',
  },
  {
    id: 'atomic',
    label: 'Âge atomique',
    sourceId: 'atomic',
    advanceCostJoules: 180000,
    description: 'L’atome apporte une énergie très dense.',
  },
  {
    id: 'fusion',
    label: 'Fusion contrôlée',
    sourceId: 'fusion',
    advanceCostJoules: 6000000,
    description: 'Allumer une étoile miniature sans la perdre.',
  },
  {
    id: 'orbital-solar',
    label: 'Solaire orbital',
    sourceId: 'orbital-solar',
    advanceCostJoules: 120000000,
    description: 'Capturer le Soleil au-dessus de la nuit.',
  },
  {
    id: 'neutron-wells',
    label: 'Puits de neutrons',
    sourceId: 'neutron-wells',
    advanceCostJoules: 1100000000,
    description: 'Accrocher des sondes aux étoiles mortes.',
  },
  {
    id: 'antimatter',
    label: 'Antimatière',
    sourceId: 'antimatter',
    advanceCostJoules: 9000000000,
    description: 'Convertir la matière elle-même en énergie.',
  },
  {
    id: 'black-hole',
    label: 'Trou noir',
    sourceId: 'black-hole',
    advanceCostJoules: 80000000000,
    description: 'Siphonner la rotation de l’infini.',
  },
  {
    id: 'dyson',
    label: 'Dyson',
    sourceId: 'dyson',
    advanceCostJoules: 950000000000,
    description: 'Construire autour d’une étoile entière.',
  },
  {
    id: 'vacuum',
    label: 'Vide',
    sourceId: 'vacuum',
    description: 'Quand l’énergie cesse d’être rare.',
  },
];

export const purchases: Purchase[] = [
  {
    id: 'campfire',
    ageId: 'biomass',
    label: 'Feu de camp',
    sourceId: 'biomass',
    description: 'Le premier objet énergétique : bois, chaleur, nourriture.',
    costJoules: 12,
    clickGain: 3,
    passiveGain: 0.4,
    assetFile: finalImagePath('biomass/island-biomass-01-built-campfire.png'),
    impactLabel: '+3 J/clic · +0.4 J/s',
  },
  {
    id: 'stone-hearth',
    ageId: 'animal-power',
    label: 'Foyer en pierre',
    sourceId: 'biomass',
    description: 'La biomasse reste centrale, mais devient plus stable.',
    costJoules: 65,
    clickGain: 2,
    passiveGain: 1.2,
    assetFile: finalImagePath('biomass/island-biomass-02-built-stone-hearth.png'),
    impactLabel: '+2 J/clic · +1.2 J/s',
  },
  {
    id: 'oxen',
    ageId: 'animal-power',
    label: 'Bœufs de traction',
    sourceId: 'animal-power',
    description: 'L’élevage ajoute une nouvelle force utile au village.',
    costJoules: 95,
    clickGain: 4,
    passiveGain: 2.2,
    assetFile: finalImagePath('animal/island-animal-02-built-oxen-pasture.png'),
    impactLabel: '+4 J/clic · +2.2 J/s',
  },
  {
    id: 'charcoal-kiln',
    ageId: 'water-wind',
    label: 'Four à charbon de bois',
    sourceId: 'biomass',
    description: 'Le bois devient un combustible plus concentré.',
    costJoules: 240,
    clickGain: 4,
    passiveGain: 6,
    assetFile: finalImagePath('biomass/island-biomass-03-built-charcoal-kiln.png'),
    impactLabel: '+4 J/clic · +6 J/s',
  },
  {
    id: 'heavy-plough',
    ageId: 'water-wind',
    label: 'Charrue lourde',
    sourceId: 'animal-power',
    description: 'La traction animale travaille mieux les sols lourds.',
    costJoules: 340,
    clickGain: 3,
    passiveGain: 8,
    assetFile: finalImagePath('animal/island-animal-03-built-heavy-plough.png'),
    impactLabel: '+3 J/clic · +8 J/s',
  },
  {
    id: 'watermill',
    ageId: 'water-wind',
    label: 'Moulin à eau',
    sourceId: 'water-wind',
    description: 'La rivière apporte une puissance mécanique continue.',
    costJoules: 480,
    clickGain: 0,
    passiveGain: 18,
    assetFile: finalImagePath('water-wind/island-water-wind-03-built-watermill.png'),
    impactLabel: '+18 J/s',
  },
  {
    id: 'wood-gasifier',
    ageId: 'fossil',
    label: 'Gazogène à bois',
    sourceId: 'biomass',
    description: 'La biomasse reste utile comme gaz combustible industriel.',
    costJoules: 1100,
    clickGain: 6,
    passiveGain: 18,
    assetFile: finalImagePath('biomass/island-biomass-04-built-wood-gasifier.png'),
    impactLabel: '+6 J/clic · +18 J/s',
  },
  {
    id: 'relay-stables',
    ageId: 'fossil',
    label: 'Relais de chevaux',
    sourceId: 'animal-power',
    description: 'Les animaux restent utiles pour déplacer hommes et matières.',
    costJoules: 1400,
    clickGain: 5,
    passiveGain: 16,
    assetFile: finalImagePath('animal/island-animal-04-built-horse-relay.png'),
    impactLabel: '+5 J/clic · +16 J/s',
  },
  {
    id: 'wind-pump',
    ageId: 'fossil',
    label: 'Pompe à vent',
    sourceId: 'water-wind',
    description: 'Le vent continue à rendre service au système productif.',
    costJoules: 1650,
    clickGain: 0,
    passiveGain: 38,
    assetFile: finalImagePath('water-wind/island-water-wind-04-built-wind-pump.png'),
    impactLabel: '+38 J/s',
  },
  {
    id: 'steam-engine',
    ageId: 'fossil',
    label: 'Machine à vapeur',
    sourceId: 'fossil',
    description: 'Le fossile débloque une densité énergétique massive.',
    costJoules: 2200,
    clickGain: 14,
    passiveGain: 72,
    assetFile: finalImagePath('fossil/island-fossil-04-built-steam-engine.png'),
    impactLabel: '+14 J/clic · +72 J/s',
  },
  {
    id: 'biogas-digester',
    ageId: 'atomic',
    label: 'Digesteur biogaz',
    sourceId: 'biomass',
    description: 'La biomasse reste présente sous une forme plus contrôlée.',
    costJoules: 4200,
    clickGain: 0,
    passiveGain: 80,
    assetFile: finalImagePath('biomass/island-biomass-05-built-biogas-digester.png'),
    impactLabel: '+80 J/s',
  },
  {
    id: 'feed-logistics',
    ageId: 'atomic',
    label: 'Logistique alimentaire',
    sourceId: 'animal-power',
    description: 'L’élevage devient une organisation de flux et de nourriture.',
    costJoules: 5200,
    clickGain: 0,
    passiveGain: 70,
    assetFile: finalImagePath('animal/island-animal-05-built-food-logistics.png'),
    impactLabel: '+70 J/s',
  },
  {
    id: 'hydro-wind-grid',
    ageId: 'atomic',
    label: 'Réseau hydro-éolien',
    sourceId: 'water-wind',
    description: 'Eau et vent restent dans le mix, mieux raccordés.',
    costJoules: 6400,
    clickGain: 0,
    passiveGain: 130,
    assetFile: finalImagePath('water-wind/island-water-wind-05-built-hydro-wind-grid.png'),
    impactLabel: '+130 J/s',
  },
  {
    id: 'thermal-turbine',
    ageId: 'atomic',
    label: 'Turbine thermique',
    sourceId: 'fossil',
    description: 'Le fossile devient un appoint puissant, mais plus encadré.',
    costJoules: 7600,
    clickGain: 16,
    passiveGain: 160,
    assetFile: finalImagePath('fossil/island-fossil-05-built-thermal-turbine.png'),
    impactLabel: '+16 J/clic · +160 J/s',
  },
  {
    id: 'reactor-core',
    ageId: 'atomic',
    label: 'Cœur de réacteur',
    sourceId: 'atomic',
    description: 'L’atome rassemble le système autour d’une source très dense.',
    costJoules: 9800,
    clickGain: 0,
    passiveGain: 420,
    assetFile: finalImagePath('atomic/island-atomic-05-built-reactor-core.png'),
    impactLabel: '+420 J/s',
  },
  {
    id: 'fusion-tokamak',
    ageId: 'fusion',
    label: 'Tokamak pilote',
    sourceId: 'fusion',
    description: 'Premier plasma confiné, puissant mais encore fragile.',
    costJoules: 180000,
    clickGain: 0,
    passiveGain: 4500,
    assetFile: finalImagePath('atomic/island-atomic-07-built-fusion-plant.png'),
    impactLabel: '+4 500 J/s',
  },
  {
    id: 'stellarator',
    ageId: 'fusion',
    label: 'Stellarator',
    sourceId: 'fusion',
    description: 'Fusion plus stable, pensée pour durer.',
    costJoules: 260000,
    clickGain: 0,
    passiveGain: 7200,
    assetFile: finalImagePath('atomic/island-atomic-07-upgraded-controlled-fusion.png'),
    impactLabel: '+7 200 J/s',
  },
  {
    id: 'laser-fusion',
    ageId: 'fusion',
    label: 'Centrale laser',
    sourceId: 'fusion',
    description: 'Impulsions de fusion à très haute densité.',
    costJoules: 420000,
    clickGain: 120,
    passiveGain: 11000,
    assetFile: FUSION_ASSET,
    impactLabel: '+120 J/clic · +11 000 J/s',
  },
  {
    id: 'orbital-collector',
    ageId: 'orbital-solar',
    label: 'Satellite collecteur',
    sourceId: 'orbital-solar',
    description: 'Un panneau solaire qui ne connaît plus la nuit.',
    costJoules: 1200000,
    clickGain: 0,
    passiveGain: 32000,
    assetFile: ORBITAL_SOLAR_ASSET,
    impactLabel: '+32 000 J/s',
  },
  {
    id: 'laser-relay',
    ageId: 'orbital-solar',
    label: 'Station relais',
    sourceId: 'orbital-solar',
    description: 'Synchronise les faisceaux entre orbite et surface.',
    costJoules: 2100000,
    clickGain: 0,
    passiveGain: 42000,
    assetFile: ORBITAL_SOLAR_ASSET,
    impactLabel: '+42 000 J/s',
  },
  {
    id: 'sps-alpha',
    ageId: 'orbital-solar',
    label: 'SPS-Alpha',
    sourceId: 'orbital-solar',
    description: 'Constellation solaire industrielle.',
    costJoules: 3600000,
    clickGain: 0,
    passiveGain: 88000,
    assetFile: ORBITAL_SOLAR_ASSET,
    impactLabel: '+88 000 J/s',
  },
  {
    id: 'pulsar-probe',
    ageId: 'neutron-wells',
    label: 'Sonde pulsar',
    sourceId: 'neutron-wells',
    description: 'Une sonde qui capte le souffle d’une étoile morte.',
    costJoules: 18000000,
    clickGain: 0,
    passiveGain: 180000,
    assetFile: finalImagePath('cosmic/island-cosmic-08-neutron-wells.png'),
    impactLabel: '+180 000 J/s',
  },
  {
    id: 'gravity-antenna',
    ageId: 'neutron-wells',
    label: 'Antenne gravitationnelle',
    sourceId: 'neutron-wells',
    description: 'Amplifie les signaux des pulsars proches.',
    costJoules: 32000000,
    clickGain: 0,
    passiveGain: 320000,
    assetFile: finalImagePath('cosmic/island-cosmic-08-neutron-wells.png'),
    impactLabel: '+320 000 J/s',
  },
  {
    id: 'neutron-mill',
    ageId: 'neutron-wells',
    label: 'Moulin à neutrons',
    sourceId: 'neutron-wells',
    description: 'Le moulin médiéval, accroché à une étoile compacte.',
    costJoules: 52000000,
    clickGain: 0,
    passiveGain: 580000,
    assetFile: finalImagePath('cosmic/island-cosmic-08-neutron-wells.png'),
    impactLabel: '+580 000 J/s',
  },
  {
    id: 'antimatter-accelerator',
    ageId: 'antimatter',
    label: 'Accélérateur orbital',
    sourceId: 'antimatter',
    description: 'Fabrique lentement de l’antimatière loin de la Terre.',
    costJoules: 160000000,
    clickGain: 0,
    passiveGain: 1200000,
    assetFile: finalImagePath('atomic/island-atomic-08-built-antimatter.png'),
    impactLabel: '+1,2 M J/s',
  },
  {
    id: 'magnetic-trap',
    ageId: 'antimatter',
    label: 'Piège magnétique',
    sourceId: 'antimatter',
    description: 'Stocke l’antimatière sans contact avec la matière.',
    costJoules: 260000000,
    clickGain: 0,
    passiveGain: 1800000,
    assetFile: finalImagePath('atomic/island-atomic-08-upgraded-antimatter-containment.png'),
    impactLabel: '+1,8 M J/s',
  },
  {
    id: 'annihilation-reactor',
    ageId: 'antimatter',
    label: 'Réacteur d’annihilation',
    sourceId: 'antimatter',
    description: 'Transforme la matière en rendement presque total.',
    costJoules: 430000000,
    clickGain: 6000,
    passiveGain: 3300000,
    assetFile: ANTIMATTER_ASSET,
    impactLabel: '+6 000 J/clic · +3,3 M J/s',
  },
  {
    id: 'ergosphere-probe',
    ageId: 'black-hole',
    label: 'Sonde ergosphérique',
    sourceId: 'black-hole',
    description: 'Traverse la zone où l’espace-temps tourne.',
    costJoules: 1200000000,
    clickGain: 0,
    passiveGain: 6200000,
    assetFile: finalImagePath('cosmic/island-cosmic-10-black-hole-siphon.png'),
    impactLabel: '+6,2 M J/s',
  },
  {
    id: 'gravity-anchor',
    ageId: 'black-hole',
    label: 'Ancrage gravitationnel',
    sourceId: 'black-hole',
    description: 'Stabilise les passes autour du trou noir.',
    costJoules: 2200000000,
    clickGain: 0,
    passiveGain: 9800000,
    assetFile: finalImagePath('cosmic/island-cosmic-10-black-hole-siphon.png'),
    impactLabel: '+9,8 M J/s',
  },
  {
    id: 'penrose-extractor',
    ageId: 'black-hole',
    label: 'Extracteur Penrose',
    sourceId: 'black-hole',
    description: 'Récupère l’énergie de rotation du trou noir.',
    costJoules: 3600000000,
    clickGain: 25000,
    passiveGain: 18000000,
    assetFile: finalImagePath('cosmic/island-cosmic-10-black-hole-siphon.png'),
    impactLabel: '+25 000 J/clic · +18 M J/s',
  },
  {
    id: 'dyson-segment',
    ageId: 'dyson',
    label: 'Segment orbital',
    sourceId: 'dyson',
    description: 'Premier morceau d’une structure autour de l’étoile.',
    costJoules: 18000000000,
    clickGain: 0,
    passiveGain: 42000000,
    assetFile: DYSON_ASSET,
    impactLabel: '+42 M J/s',
  },
  {
    id: 'space-foundry',
    ageId: 'dyson',
    label: 'Fonderie spatiale',
    sourceId: 'dyson',
    description: 'Transforme les astéroïdes en matériaux orbitaux.',
    costJoules: 32000000000,
    clickGain: 0,
    passiveGain: 68000000,
    assetFile: DYSON_ASSET,
    impactLabel: '+68 M J/s',
  },
  {
    id: 'energy-distribution',
    ageId: 'dyson',
    label: 'Réseau stellaire',
    sourceId: 'dyson',
    description: 'Distribue l’énergie de l’étoile entière.',
    costJoules: 52000000000,
    clickGain: 0,
    passiveGain: 140000000,
    assetFile: DYSON_ASSET,
    impactLabel: '+140 M J/s',
  },
  {
    id: 'casimir-fluctuator',
    ageId: 'vacuum',
    label: 'Fluctuateur Casimir',
    sourceId: 'vacuum',
    description: 'Force le vide quantique à révéler son énergie.',
    costJoules: 160000000000,
    clickGain: 0,
    passiveGain: 320000000,
    assetFile: finalImagePath('cosmic/island-cosmic-12-vacuum-universe-seed.png'),
    impactLabel: '+320 M J/s',
  },
  {
    id: 'vacuum-lattice',
    ageId: 'vacuum',
    label: 'Réseau du vide',
    sourceId: 'vacuum',
    description: 'Stabilise les fluctuations au lieu de les subir.',
    costJoules: 260000000000,
    clickGain: 0,
    passiveGain: 620000000,
    assetFile: finalImagePath('cosmic/island-cosmic-12-vacuum-universe-seed.png'),
    impactLabel: '+620 M J/s',
  },
  {
    id: 'universe-seed',
    ageId: 'vacuum',
    label: 'Graine d’univers',
    sourceId: 'vacuum',
    description: 'Toute l’énergie devient une question de destination.',
    costJoules: 420000000000,
    clickGain: 0,
    passiveGain: 1200000000,
    assetFile: finalImagePath('cosmic/island-cosmic-12-vacuum-universe-seed.png'),
    impactLabel: '+1,2 Md J/s',
  },
];

export const technologies: Technology[] = [
  {
    id: 'ember-keeping',
    ageId: 'biomass',
    label: 'Conservation de la braise',
    sourceId: 'biomass',
    targetPurchaseId: 'campfire',
    costJoules: 24,
    clickGain: 2,
    passiveGain: 0.8,
    assetFile: finalImagePath('biomass/island-biomass-01-upgraded-ember-keeping.png'),
    impactLabel: '+2 J/clic · +0.8 J/s',
  },
  {
    id: 'masonry-hearth',
    ageId: 'animal-power',
    label: 'Foyer maçonné',
    sourceId: 'biomass',
    targetPurchaseId: 'stone-hearth',
    costJoules: 95,
    clickGain: 2,
    passiveGain: 1.5,
    assetFile: finalImagePath('biomass/island-biomass-02-upgraded-masonry-hearth.png'),
    impactLabel: '+2 J/clic · +1.5 J/s',
  },
  {
    id: 'animal-domestication',
    ageId: 'animal-power',
    label: 'Domestication de traction',
    sourceId: 'animal-power',
    targetPurchaseId: 'oxen',
    costJoules: 130,
    clickGain: 2,
    passiveGain: 2.4,
    assetFile: finalImagePath('animal/island-animal-02-upgraded-animal-domestication.png'),
    impactLabel: '+2 J/clic · +2.4 J/s',
  },
  {
    id: 'charcoal-craft',
    ageId: 'water-wind',
    label: 'Charbonnage',
    sourceId: 'biomass',
    targetPurchaseId: 'charcoal-kiln',
    costJoules: 340,
    clickGain: 3,
    passiveGain: 6,
    assetFile: finalImagePath('biomass/island-biomass-03-upgraded-charcoal-craft.png'),
    impactLabel: '+3 J/clic · +6 J/s',
  },
  {
    id: 'shoulder-collar',
    ageId: 'water-wind',
    label: 'Collier d’épaule',
    sourceId: 'animal-power',
    targetPurchaseId: 'heavy-plough',
    costJoules: 440,
    clickGain: 2,
    passiveGain: 8,
    assetFile: finalImagePath('animal/island-animal-03-upgraded-shoulder-collar.png'),
    impactLabel: '+2 J/clic · +8 J/s',
  },
  {
    id: 'wind-gears',
    ageId: 'water-wind',
    label: 'Moulin à vent',
    sourceId: 'water-wind',
    targetPurchaseId: 'watermill',
    costJoules: 560,
    clickGain: 0,
    passiveGain: 16,
    assetFile: finalImagePath('water-wind/island-water-wind-03-upgraded-windmill.png'),
    impactLabel: '+16 J/s',
  },
  {
    id: 'wood-gas-process',
    ageId: 'fossil',
    label: 'Gaz de bois',
    sourceId: 'biomass',
    targetPurchaseId: 'wood-gasifier',
    costJoules: 1300,
    clickGain: 4,
    passiveGain: 18,
    assetFile: finalImagePath('biomass/island-biomass-04-upgraded-wood-gas-process.png'),
    impactLabel: '+4 J/clic · +18 J/s',
  },
  {
    id: 'horse-logistics',
    ageId: 'fossil',
    label: 'Haras logistiques',
    sourceId: 'animal-power',
    targetPurchaseId: 'relay-stables',
    costJoules: 1500,
    clickGain: 3,
    passiveGain: 16,
    assetFile: finalImagePath('animal/island-animal-04-upgraded-horse-logistics.png'),
    impactLabel: '+3 J/clic · +16 J/s',
  },
  {
    id: 'mechanical-pumps',
    ageId: 'fossil',
    label: 'Pompes mécaniques',
    sourceId: 'water-wind',
    targetPurchaseId: 'wind-pump',
    costJoules: 1800,
    clickGain: 0,
    passiveGain: 40,
    assetFile: finalImagePath('water-wind/island-water-wind-04-upgraded-mechanical-pumps.png'),
    impactLabel: '+40 J/s',
  },
  {
    id: 'high-pressure-steam',
    ageId: 'fossil',
    label: 'Vapeur haute pression',
    sourceId: 'fossil',
    targetPurchaseId: 'steam-engine',
    costJoules: 2400,
    clickGain: 10,
    passiveGain: 90,
    assetFile: finalImagePath('fossil/island-fossil-04-upgraded-high-pressure-steam.png'),
    impactLabel: '+10 J/clic · +90 J/s',
  },
  {
    id: 'biogas-process',
    ageId: 'atomic',
    label: 'Méthanisation',
    sourceId: 'biomass',
    targetPurchaseId: 'biogas-digester',
    costJoules: 5000,
    clickGain: 0,
    passiveGain: 95,
    assetFile: finalImagePath('biomass/island-biomass-05-upgraded-methanization.png'),
    impactLabel: '+95 J/s',
  },
  {
    id: 'feed-chain',
    ageId: 'atomic',
    label: 'Chaîne alimentaire',
    sourceId: 'animal-power',
    targetPurchaseId: 'feed-logistics',
    costJoules: 6000,
    clickGain: 0,
    passiveGain: 85,
    assetFile: finalImagePath('animal/island-animal-05-upgraded-food-chain.png'),
    impactLabel: '+85 J/s',
  },
  {
    id: 'modern-wind-turbines',
    ageId: 'atomic',
    label: 'Éoliennes modernes',
    sourceId: 'water-wind',
    targetPurchaseId: 'hydro-wind-grid',
    costJoules: 7400,
    clickGain: 0,
    passiveGain: 180,
    assetFile: finalImagePath('water-wind/island-water-wind-05-upgraded-modern-wind-turbines.png'),
    impactLabel: '+180 J/s',
  },
  {
    id: 'thermal-cycle',
    ageId: 'atomic',
    label: 'Cycle thermique',
    sourceId: 'fossil',
    targetPurchaseId: 'thermal-turbine',
    costJoules: 8600,
    clickGain: 10,
    passiveGain: 200,
    assetFile: finalImagePath('fossil/island-fossil-05-upgraded-thermal-cycle.png'),
    impactLabel: '+10 J/clic · +200 J/s',
  },
  {
    id: 'controlled-fission',
    ageId: 'atomic',
    label: 'Fission contrôlée',
    sourceId: 'atomic',
    targetPurchaseId: 'reactor-core',
    costJoules: 11500,
    clickGain: 0,
    passiveGain: 520,
    assetFile: finalImagePath('atomic/island-atomic-05-upgraded-controlled-fission.png'),
    impactLabel: '+520 J/s',
  },
  {
    id: 'plasma-confinement',
    ageId: 'fusion',
    label: 'Plasma confiné',
    sourceId: 'fusion',
    targetPurchaseId: 'fusion-tokamak',
    costJoules: 520000,
    clickGain: 0,
    passiveGain: 8000,
    assetFile: finalImagePath('atomic/island-atomic-07-upgraded-controlled-fusion.png'),
    impactLabel: '+8 000 J/s',
  },
  {
    id: 'laser-compression',
    ageId: 'fusion',
    label: 'Compression laser',
    sourceId: 'fusion',
    targetPurchaseId: 'laser-fusion',
    costJoules: 780000,
    clickGain: 80,
    passiveGain: 11000,
    assetFile: FUSION_UPGRADED_ASSET,
    impactLabel: '+80 J/clic · +11 000 J/s',
  },
  {
    id: 'coherent-transmission',
    ageId: 'orbital-solar',
    label: 'Transmission cohérente',
    sourceId: 'orbital-solar',
    targetPurchaseId: 'laser-relay',
    costJoules: 4800000,
    clickGain: 0,
    passiveGain: 55000,
    assetFile: ORBITAL_SOLAR_ASSET,
    impactLabel: '+55 000 J/s',
  },
  {
    id: 'orbital-phase-lock',
    ageId: 'orbital-solar',
    label: 'Verrouillage orbital',
    sourceId: 'orbital-solar',
    targetPurchaseId: 'sps-alpha',
    costJoules: 7500000,
    clickGain: 0,
    passiveGain: 85000,
    assetFile: ORBITAL_SOLAR_ASSET,
    impactLabel: '+85 000 J/s',
  },
  {
    id: 'pulsar-mapping',
    ageId: 'neutron-wells',
    label: 'Cartographie pulsar',
    sourceId: 'neutron-wells',
    targetPurchaseId: 'pulsar-probe',
    costJoules: 78000000,
    clickGain: 0,
    passiveGain: 480000,
    assetFile: finalImagePath('cosmic/island-cosmic-08-neutron-wells.png'),
    impactLabel: '+480 000 J/s',
  },
  {
    id: 'neutron-orbits',
    ageId: 'neutron-wells',
    label: 'Orbites neutroniques',
    sourceId: 'neutron-wells',
    targetPurchaseId: 'neutron-mill',
    costJoules: 120000000,
    clickGain: 0,
    passiveGain: 780000,
    assetFile: finalImagePath('cosmic/island-cosmic-08-neutron-wells.png'),
    impactLabel: '+780 000 J/s',
  },
  {
    id: 'magnetic-bottles',
    ageId: 'antimatter',
    label: 'Bouteilles magnétiques',
    sourceId: 'antimatter',
    targetPurchaseId: 'magnetic-trap',
    costJoules: 620000000,
    clickGain: 0,
    passiveGain: 2600000,
    assetFile: finalImagePath('atomic/island-atomic-08-upgraded-antimatter-containment.png'),
    impactLabel: '+2,6 M J/s',
  },
  {
    id: 'controlled-annihilation',
    ageId: 'antimatter',
    label: 'Annihilation contrôlée',
    sourceId: 'antimatter',
    targetPurchaseId: 'annihilation-reactor',
    costJoules: 960000000,
    clickGain: 8000,
    passiveGain: 3600000,
    assetFile: ANTIMATTER_UPGRADED_ASSET,
    impactLabel: '+8 000 J/clic · +3,6 M J/s',
  },
  {
    id: 'kerr-measure',
    ageId: 'black-hole',
    label: 'Mesure de Kerr',
    sourceId: 'black-hole',
    targetPurchaseId: 'ergosphere-probe',
    costJoules: 5200000000,
    clickGain: 0,
    passiveGain: 14000000,
    assetFile: finalImagePath('cosmic/island-cosmic-10-black-hole-siphon.png'),
    impactLabel: '+14 M J/s',
  },
  {
    id: 'penrose-stability',
    ageId: 'black-hole',
    label: 'Stabilité Penrose',
    sourceId: 'black-hole',
    targetPurchaseId: 'penrose-extractor',
    costJoules: 8200000000,
    clickGain: 18000,
    passiveGain: 26000000,
    assetFile: finalImagePath('cosmic/island-cosmic-10-black-hole-siphon.png'),
    impactLabel: '+18 000 J/clic · +26 M J/s',
  },
  {
    id: 'dyson-swarm',
    ageId: 'dyson',
    label: 'Essaim de Dyson',
    sourceId: 'dyson',
    targetPurchaseId: 'dyson-segment',
    costJoules: 120000000000,
    clickGain: 0,
    passiveGain: 180000000,
    assetFile: DYSON_ASSET,
    impactLabel: '+180 M J/s',
  },
  {
    id: 'stellar-governance',
    ageId: 'dyson',
    label: 'Gouvernance stellaire',
    sourceId: 'dyson',
    targetPurchaseId: 'energy-distribution',
    costJoules: 180000000000,
    clickGain: 0,
    passiveGain: 320000000,
    assetFile: DYSON_ASSET,
    impactLabel: '+320 M J/s',
  },
  {
    id: 'heliosphere-routing',
    ageId: 'dyson',
    label: 'Routage héliosphérique',
    sourceId: 'dyson',
    targetPurchaseId: 'energy-distribution',
    costJoules: 300000000000,
    clickGain: 0,
    passiveGain: 420000000,
    assetFile: DYSON_ASSET,
    impactLabel: '+420 M J/s',
  },
  {
    id: 'casimir-geometry',
    ageId: 'vacuum',
    label: 'Géométrie Casimir',
    sourceId: 'vacuum',
    targetPurchaseId: 'casimir-fluctuator',
    costJoules: 520000000000,
    clickGain: 0,
    passiveGain: 900000000,
    assetFile: finalImagePath('cosmic/island-cosmic-12-vacuum-universe-seed.png'),
    impactLabel: '+900 M J/s',
  },
  {
    id: 'cosmic-reboot',
    ageId: 'vacuum',
    label: 'Recommencement cosmique',
    sourceId: 'vacuum',
    targetPurchaseId: 'universe-seed',
    costJoules: 900000000000,
    clickGain: 0,
    passiveGain: 1800000000,
    assetFile: finalImagePath('cosmic/island-cosmic-12-vacuum-universe-seed.png'),
    impactLabel: '+1,8 Md J/s',
  },
];

export const breakthroughMilestones: BreakthroughMilestone[] = [
  {
    id: 'first-steam',
    trigger: { type: 'purchase', id: 'steam-engine' },
    kicker: 'Percée',
    title: 'La vapeur pousse le monde',
    detail: 'Le feu quitte le foyer et devient une force mécanique.',
    tone: 'steam',
  },
  {
    id: 'first-fission',
    trigger: { type: 'technology', id: 'controlled-fission' },
    kicker: 'Percée',
    title: 'Le noyau devient moteur',
    detail: 'Une petite masse remplace des montagnes de combustible.',
    tone: 'atomic',
  },
  {
    id: 'first-fusion',
    trigger: { type: 'technology', id: 'plasma-confinement' },
    kicker: 'Percée',
    title: 'Une étoile tenue en laisse',
    detail: 'La production change d’échelle sans brûler la planète.',
    tone: 'stellar',
  },
  {
    id: 'first-orbital-solar',
    trigger: { type: 'purchase', id: 'orbital-collector' },
    kicker: 'Percée',
    title: 'Le jour ne finit plus',
    detail: 'Le Soleil alimente le système depuis l’orbite.',
    tone: 'stellar',
  },
  {
    id: 'first-neutron-well',
    trigger: { type: 'technology', id: 'pulsar-mapping' },
    kicker: 'Percée',
    title: 'Une étoile morte travaille',
    detail: 'Les pulsars deviennent des repères et des moteurs.',
    tone: 'cosmic',
  },
  {
    id: 'first-antimatter-bottle',
    trigger: { type: 'technology', id: 'magnetic-bottles' },
    kicker: 'Percée',
    title: 'La matière inversée tient',
    detail: 'Le stockage magnétique rend l’antimatière utilisable.',
    tone: 'atomic',
  },
  {
    id: 'first-controlled-annihilation',
    trigger: { type: 'technology', id: 'controlled-annihilation' },
    kicker: 'Percée',
    title: 'L’annihilation devient utile',
    detail: 'Le rendement maximal cesse d’être une catastrophe et devient un moteur.',
    tone: 'atomic',
  },
  {
    id: 'black-hole-threshold',
    trigger: { type: 'age', id: 'black-hole' },
    kicker: 'Transition',
    title: 'L’horizon entre dans le plan',
    detail: 'L’énergie n’est plus seulement dans la matière, mais dans la géométrie.',
    tone: 'cosmic',
  },
  {
    id: 'first-black-hole-siphon',
    trigger: { type: 'technology', id: 'kerr-measure' },
    kicker: 'Percée',
    title: 'La gravité devient turbine',
    detail: 'Le système apprend à lire la rotation d’un trou noir.',
    tone: 'cosmic',
  },
  {
    id: 'penrose-loop-locked',
    trigger: { type: 'technology', id: 'penrose-stability' },
    kicker: 'Percée',
    title: 'L’horizon tourne pour nous',
    detail: 'Le siphon cesse d’être une expérience et devient une boucle stable.',
    tone: 'cosmic',
  },
  {
    id: 'first-stellar-orbit',
    trigger: { type: 'age', id: 'dyson' },
    kicker: 'Transition',
    title: 'L’étoile devient chantier',
    detail: 'La civilisation quitte les mondes et construit dans la lumière.',
    tone: 'stellar',
  },
  {
    id: 'first-dyson-segment',
    trigger: { type: 'purchase', id: 'dyson-segment' },
    kicker: 'Percée',
    title: 'Premier morceau d’étoile',
    detail: 'La construction quitte les planètes et vise l’orbite stellaire.',
    tone: 'stellar',
  },
  {
    id: 'first-dyson-ring',
    trigger: { type: 'technology', id: 'dyson-swarm' },
    kicker: 'Percée',
    title: 'Premier anneau stellaire',
    detail: 'Le village entoure maintenant une étoile entière.',
    tone: 'stellar',
  },
  {
    id: 'stellar-grid-online',
    trigger: { type: 'technology', id: 'stellar-governance' },
    kicker: 'Percée',
    title: 'Le réseau stellaire répond',
    detail: 'L’énergie d’une étoile devient une infrastructure gouvernée.',
    tone: 'stellar',
  },
  {
    id: 'stellar-arteries',
    trigger: { type: 'technology', id: 'heliosphere-routing' },
    kicker: 'Percée',
    title: 'Les artères solaires s’ouvrent',
    detail: 'Le réseau apprend à router l’énergie avant même qu’elle touche une planète.',
    tone: 'stellar',
  },
  {
    id: 'vacuum-threshold',
    trigger: { type: 'age', id: 'vacuum' },
    kicker: 'Transition',
    title: 'Le bord du vide apparaît',
    detail: 'Après l’étoile, il ne reste plus qu’à interroger l’espace lui-même.',
    tone: 'cosmic',
  },
  {
    id: 'first-casimir-contact',
    trigger: { type: 'purchase', id: 'casimir-fluctuator' },
    kicker: 'Percée',
    title: 'Premier contact Casimir',
    detail: 'Le vide commence à produire au lieu de seulement séparer.',
    tone: 'cosmic',
  },
  {
    id: 'first-vacuum-seed',
    trigger: { type: 'purchase', id: 'universe-seed' },
    kicker: 'Percée',
    title: 'Le vide répond',
    detail: 'L’énergie cesse d’être une limite et devient un choix.',
    tone: 'cosmic',
  },
];
